# Generated by Django 4.2.4 on 2023-08-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('cupo', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('jornada', models.CharField(choices=[('Ma', 'Mañana'), ('Ta', 'Tarde'), ('No', 'Noche')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.programa')),
            ],
        ),
    ]
